ASSIGNMENT - 2 Data type and Structure


---

Que 1 :  What are data structures, and why are they important?
 - Data structures are specialized formats for organizing, storing, and accessing collections of data.They provide efficient ways to manage information based on its characteristics and intended use.
 - Choosing the right data structure significantly impacts the efficiency and performance of your program.
  - Well-chosen data structures can:
- Simplify data manipulation (adding, removing, modifying elements)
- Optimize searching and sorting operations
- Conserve memory usage.

Que 2 :  Explain the difference between mutable and immutable data types with examples.
  - Mutable data types are those that allow modification of their content without changing their identity.
   - list, dictionary & set is mutable data types.

In [ ]:
#example of mutable data types
my_list = [1, 2, 3]
my_list[0] = 10
print(my_list)

[10, 2, 3]

-  immutable data types not allow any modification once after created.
- tuples , strings & number are immutable data types.

In [ ]:
#example of immutable data types
my_tuple = (1, 2, 3)
my_tuple[0] = 10
print(my_tuple)

TypeError: 'tuple' object does not support item assignment

Que 3 :  What are the main differences between lists and tuples in Python?
  - mutability is the main diffrence between list and tuple:
  lists is mutable and tuple is immutable data type.
  - list has append , add and remove in-built mathod.
  - tuple has index and count mathod.

Que 4 :  Describe how dictionaries store data.
  -  dictionary data types stores data in key value pair.

Que 5 :  Why might you use a set instead of a list in Python.
  - use a set when you need unique elements, faster membership tests, or need to perform set operations. For ordered collections or when duplicates are allowed, a list might be more appropriate.

Que 6 :  What is a string in Python, and how is it different from a list ?
  - A string in Python is a sequence of characters enclosed within single quotes ('), double quotes ("), or triple quotes (''' or """). Strings are used to represent text data.
  - string is basically used for text manipulation.

Que 7 :  How do tuples ensure data integrity in Python?
  - Tuples in Python are a powerful tool for ensuring data integrity due to their immutable nature and also because of hashability, predictable behaveior and data grouping.

Que 8 :  What is a hash table, and how does it relate to dictionaries in Python?
-  A hash table is a data structure that allows for efficient insertion, lookup, and deletion of key-value pairs. In Python, the built-in dictionary (dict) is an implementation of a hash table.

Que 9 :  Can lists contain different data types in Python?
  -  lists are incredibly versatile and can contain elements of different data types. For example, you can have integers, strings, floats, and even other lists all in a single list.

Que 10 :  Explain why strings are immutable in Python?
 -  Strings in Python are “immutable” which means they can not be changed after they are created.The immutability of Python string is very useful as it helps in hashing, performance optimization, safety, ease of use, etc.

Que 11 :  What advantages do dictionaries offer over lists for certain tasks?
  - Dictionalries offers to store data into a key value pair. so that we can apply modification on key is become easier. and other side list can not provide this type of modification facality.

Que 12 :  Describe a scenario where using a tuple would be preferable over a list ?
  -  when which data will not change in future then we can use tuple over list.

Que 13 :  How do sets handle duplicate values in Python?
-  sets are a collection type that automatically handle duplicate values by ensuring that each element is unique. When you add elements to a set, any duplicate values are automatically removed.

Que 14 :  How does the “in” keyword work differently for lists and dictionaries ?
-  in list, It iterates through each element of the list, comparing the given element with each item. It returns True if a match is found, otherwise False.
- and in dictionaries, It directly searches for the given key in the dictionary's keys. It returns True if the key is found, otherwise False.

Que 15 :  Can you modify the elements of a tuple? Explain why or why not?
-  No, tuple is immutable data type that's why we can not modify data in it.

Que 16 :  What is a nested dictionary, and give an example of its use case.
-  A nested dictionary is simply a dictionary within another dictionary. It's a way to organize data in a hierarchical structure. You can think of it like having a main dictionary that contains other dictionaries as its values.

In [ ]:
#example of nested dictionary
employees = {
    "employee1": {
        "name": "Alice",
        "age": 30,
        "department": "Sales"
    },
    "employee2": {
        "name": "Bob",
        "age": 35,
        "department": "Engineering"
    }
}
employees

{'employee1': {'name': 'Alice', 'age': 30, 'department': 'Sales'},
 'employee2': {'name': 'Bob', 'age': 35, 'department': 'Engineering'}}

Que 18 :  In what situations are lists preferred over dictionaries?
-  when we want to store data in pair of key and
 value.

Que 19 :  Why are dictionaries considered unordered, and how does that affect data retrieval?
-  the items in a dictionary do not have an inherent positional index like they do in a list or an array. Instead of using numerical indices to access elements, a dictionary uses keys to uniquely identify and retrieve values associated with those keys.

Que 20 :  Explain the difference between a list and a dictionary in terms of data retrieval.
-  A list is a data structure designed for efficient iteration and sequential access. A dictionary is an implementation of a hash table designed for random access.



---
 Prectical Question :



---

Que 1 :  Write a code to create a string with your name and print it?

In [1]:
str1 = "surbhi"
print(str1)

surbhi

Que 2 :  Write a code to find the length of the string "Hello World"

In [2]:
str1 = "hello world"
print(len(str1))

11

Que 3 :  Write a code to slice the first 3 characters from the string "Python Programming"

In [3]:
str1 = "python programming"
print(str1[0:3])

pyt

Que 4 :  Write a code to convert the string "hello" to uppercase .

In [4]:
str1 = "hello"
print(str1.upper())

HELLO

Que 5 :  Write a code to replace the word "apple" with "orange" in the string "I like apple"

In [5]:
str1 = "i like apple"
print(str1.replace("apple","orange"))

i like orange

Que 6 :  Write a code to create a list with numbers 1 to 5 and print it.

In [6]:
my_list = [1,2,3,4,5]
print(my_list)

[1, 2, 3, 4, 5]

Que 7 :  Write a code to append the number 10 to the list [1, 2, 3, 4]

In [7]:
my_list = [1,2,3,4]
my_list.append(10)
print(my_list)

[1, 2, 3, 4, 10]

Que 8 :  Write a code to remove the number 3 from the list [1, 2, 3, 4, 5]

In [8]:
my_list = [1,2,3,4,5]
my_list.remove(3)
print(my_list)

[1, 2, 4, 5]

Que 9 :  Write a code to access the second element in the list ['a', 'b', 'c', 'd']

In [9]:
my_list = ['a','b','c','d']
print(my_list[1])

b

Que 10 :  Write a code to reverse the list [10, 20, 30, 40, 50].

In [10]:
my_list = [10,20,30,40,50]
print(my_list[::-1])

[50, 40, 30, 20, 10]

Que 11 : Write a code to create a tuple with the elements 10, 20, 30 and print it.

In [11]:
my_tuple = (10,20,30)
print(my_tuple)

(10, 20, 30)

Que 12 :  Write a code to access the first element of the tuple ('apple', 'banana', 'cherry').

In [12]:
my_tuple = ('apple','banana','cherry')
print(my_tuple[0])

apple

Que 13 : Write a code to count how many times the number 2 appears in the tuple (1, 2, 3, 2, 4, 2)

In [13]:
my_tuple = (1,2,3,2,4,2)
print(my_tuple.count(2))

3

Que 14 : Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit').

In [14]:
my_tuple = ('dog','cat','rabbit')
print(my_tuple.index('cat'))

1

Que 15 :  Write a code to check if the element "banana" is in the tuple ('apple', 'orange', 'banana').

In [15]:
my_tuple = ('apple','orange','banana')
print('banana' in my_tuple)

True

Que 16: Write a code to create a set with the elements 1, 2, 3, 4, 5 and print it.

In [16]:
my_set = {1,2,3,4,5}
print(my_set)

{1, 2, 3, 4, 5}

Que 17 :  17. Write a code to add the element 6 to the set {1, 2, 3, 4}.

In [17]:
my_set = {1,2,3,4}
my_set.add(6)
print(my_set)

{1, 2, 3, 4, 6}

Que  18. Write a code to create a tuple with the elements 10, 20, 30 and print it.

In [18]:
my_tuple = (10,20,30)
print(my_tuple)

(10, 20, 30)

Que  19. Write a code to access the first element of the tuple ('apple', 'banana', 'cherry').

In [19]:
my_tuple = ('apple','banana','cherry')
print(my_tuple[0])

apple

Que  20. Write a code to count how many times the number 2 appears in the tuple (1, 2, 3, 2, 4, 2).

In [20]:
my_tuple = (1,2,3,2,4,2)
print(my_tuple.count(2))

3

Que  21. Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit').

In [21]:
my_tuple = ('dog','cat','rabbit')
print(my_tuple.index('cat'))

1

Que  22. Write a code to check if the element "banana" is in the tuple ('apple', 'orange', 'banana').

In [22]:
my_tuple = ('apple','orange','banana')
print('banana' in my_tuple)

True

Que  23. Write a code to create a set with the elements 1, 2, 3, 4, 5 and print it.

In [23]:
my_set = {1,2,3,4,5}
print(my_set)

{1, 2, 3, 4, 5}

Que  24. Write a code to add the element 6 to the set {1, 2, 3, 4}.

In [24]:
my_set = {1,2,3,4}
my_set.add(6)
print(my_set)

{1, 2, 3, 4, 6}